### ISSUE TITLE
Permalink variables

### ISSUE THREAD

**Issue by wlabarron** [bluszcz/jekyll-strapi#25]
Hello, I'm struggling to get the `:variable` permalink structure working like in the Strapi v3 version of the plugin.

`permalink: /:id` works as expected with the Strapi record ID in the permalink, but using the name of other fields in the content type (like `permalink: /:link` to put the "link" field in) doesn't work and gives this error:

```
/opt/homebrew/lib/ruby/gems/3.1.0/gems/addressable-2.8.1/lib/addressable/uri.rb:2353:in `to_s': Cannot assemble URI string with ambiguous path: ':link' (Addressable::URI::InvalidURIError)
```

Is there something I need to enable or change to make this work? Thank you!

**Comment by bluszcz** [comment]
Helo, this one works only with Strapi 4...

**Comment by wlabarron** [comment]
Hello, I'm using Strapi v4. I meant that in the previous version I was able to use `:link` etc in permalinks, but that doesn't work in this version.

**Comment by bluszcz** [comment]
@mkrajewski90 have been working on permalinks - any quick comment here perhaps? :)

**Comment by mkrajewski90** [comment]
@wlabarron - could you give me a config code example, please?

**Comment by wlabarron** [comment]
Sure! I've got a field in Strapi named `link`, and my Jekyll config looks like this:
``` yaml
plugins:
  - jekyll-strapi-4

strapi:  
    # Your API endpoint (optional, default to http://localhost:1337)
    endpoint: http://localhost:1337
    # Collections, key is used to access in the strapi.collections template variable
    collections:
        pages:
            # Collection name . Used to construct the url requested. Example: type `foo` would generate the following url `http://localhost:1337/foo`.
            type: pages
            # Permalink used to generate the output files (eg. /posts/:id).
            permalink: /:link
            # Layout file for this collection
            layout: default.html
            # Generate output files or not (default: false)
            output: true
```
